package com.sistemasoperativos.denny.rssreader.models;

import java.util.ArrayList;

/**
 * Created by denny on 6/11/15.
 */
public class Buffer {

  private ArrayList<Feed> feeds;

  public Buffer() {
    feeds = new ArrayList<>();
  }

  /**
   * Adds a feed generated by a producer.
   *
   * @param  feed  an information block to be used by a consumer
   * @see          Feed
   */
  public synchronized void addFeed(Feed feed) {
    feeds.add(feed);
  }

  /**
   * Returns the first Feed of the list.
   *
   * @return  an information block to be used by a consumer
   * @see     Feed
   */
  public synchronized Feed getFeed() {
    Feed feed = null;
    if (!feeds.isEmpty()) {
      feed = feeds.remove(0);
    }
    return feed;
  }

}
